name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: curl -L "https://github.com/SAP/cloud-mta-build-tool/releases/download/v1.0.15/cloud-mta-build-tool_1.0.15_Linux_amd64.tar.gz" | sudo tar -zx -C /usr/local/bin
      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - name: npmExecuteLint
        uses: SAP/project-piper-action@master
        with:
          command: npmExecuteLint
      - run: npm audit
      - run: echo simulate prod deploy && sleep 90
