name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - name: npmExecuteLint
        uses: SAP/project-piper-action@master
        with:
          command: npmExecuteLint
      - run: npm audit
      - run: echo simulate prod deploy && sleep 90
